# Generated by Django 5.2.11 on 2026-04-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("verification", "Email Verification"),
                    ("password_reset", "Password Reset"),
                    ("welcome", "Welcome Email"),
                    ("notification", "General Notification"),
                    ("answer_notification", "Answer Notification"),
                    ("comment_notification", "Comment Notification"),
                    ("follow_notification", "Follow Notification"),
                    (
                        "kids_teacher_welcome",
                        "Marifetli Kids — Öğretmen hesabı (geçici şifre)",
                    ),
                    (
                        "kids_parent_new_test",
                        "Marifetli Kids — Veliye yeni test bildirimi",
                    ),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
