# Generated by Django 5.2.11 on 2026-03-01 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
        ("questions", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="categories.category",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="question",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="hot_score",
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="question",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="question",
            name="meta_description",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="question",
            name="meta_title",
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name="tag",
            name="question_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tag",
            name="slug",
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
        migrations.CreateModel(
            name="TagFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="questions.tag",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_follows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "tag")},
            },
        ),
    ]
