# Generated by Django 5.2.11 on 2026-03-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0003_question_category_question_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("open", "Open"),
                    ("closed", "Closed"),
                    ("archived", "Archived"),
                ],
                default="open",
                max_length=10,
            ),
        ),
    ]
