# Generated by Django 5.2.11 on 2026-03-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("answers", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="answer",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
