# Generated by Django 5.2.11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("answers", "0003_answer_deleted_at_answer_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="answers.answer",
            ),
        ),
    ]
