# Generated by Django - Initial achievement data

from django.db import migrations


def create_achievements(apps, schema_editor):
    AchievementCategory = apps.get_model('achievements', 'AchievementCategory')
    Achievement = apps.get_model('achievements', 'Achievement')

    categories_data = [
        {'slug': 'basiarken', 'name': 'Başlarken', 'order': 1},
        {'slug': 'kesif', 'name': 'Keşif', 'order': 2},
        {'slug': 'topluluk', 'name': 'Topluluk', 'order': 3},
        {'slug': 'uzman', 'name': 'Uzman', 'order': 4},
    ]
    cats = {}
    for c in categories_data:
        cat, _ = AchievementCategory.objects.get_or_create(slug=c['slug'], defaults=c)
        cats[c['slug']] = cat

    achievements_data = [
        ('basiarken', 'secured_account', 'Güvenli Hesap', 'E-posta adresinizi doğruladınız', '🔒', 1),
        ('basiarken', 'newcomer', 'Yeni Üye', 'Marifetli\'ye katıldınız', '🎉', 2),
        ('basiarken', 'profile_perfectionist', 'Profil Mükemmelleştirici', 'Profil bilgilerinizi tamamladınız', '✨', 3),
        ('basiarken', 'first_question', 'İlk Soru', 'İlk sorunuzu sordunuz', '❓', 4),
        ('kesif', 'sharing_enthusiast', 'Paylaşım Sever', '5 soru sordunuz', '📤', 1),
        ('kesif', 'question_expert_10', 'Soru Ustası (10)', '10 soru sordunuz', '📝', 2),
        ('kesif', 'question_master_100', 'Soru Dehası (100)', '100 soru sordunuz', '🏆', 3),
        ('kesif', 'answer_expert_10', 'Cevap Ustası (10)', '10 cevap yazdınız', '💬', 4),
        ('kesif', 'answer_master_100', 'Cevap Dehası (100)', '100 cevap yazdınız', '🎯', 5),
        ('topluluk', 'best_answer_selected', 'En İyi Cevap', 'Cevabınız en iyi seçildi', '⭐', 1),
        ('topluluk', 'reputation_100', 'İtibar 100', '100 itibar puanına ulaştınız', '📈', 2),
        ('topluluk', 'reputation_1000', 'İtibar 1000', '1000 itibar puanına ulaştınız', '🌟', 3),
        ('topluluk', 'popular_10', 'Popüler', '10 takipçiniz oldu', '❤️', 4),
    ]
    for cat_slug, code, name, desc, icon, order in achievements_data:
        Achievement.objects.get_or_create(
            code=code,
            defaults={
                'category': cats[cat_slug],
                'name': name,
                'description': desc,
                'icon': icon,
                'order': order,
            }
        )


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_achievements, reverse_func),
    ]
