# Generated by Django 5.2.11 on 2026-03-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="Marifetli", max_length=200)),
                ("site_description", models.TextField(blank=True)),
                ("contact_email", models.EmailField(max_length=254)),
                ("is_maintenance_mode", models.BooleanField(default=False)),
                ("maintenance_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Site Configurations",
            },
        ),
    ]
