# Generated by Django 5.2.11 on 2026-03-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMediaLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter / X"),
                            ("instagram", "Instagram"),
                            ("youtube", "YouTube"),
                            ("linkedin", "LinkedIn"),
                            ("tiktok", "TikTok"),
                            ("other", "Diğer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField()),
                (
                    "label",
                    models.CharField(
                        blank=True, help_text="İsteğe bağlı görünen ad", max_length=100
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Sosyal medya linki",
                "verbose_name_plural": "Sosyal medya linkleri",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AlterModelOptions(
            name="siteconfiguration",
            options={
                "verbose_name": "Site ayarları",
                "verbose_name_plural": "Site ayarları",
            },
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="contact_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="contact_description",
            field=models.TextField(
                blank=True, help_text="İletişim sayfasında gösterilecek kısa açıklama"
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="google_analytics_id",
            field=models.CharField(
                blank=True, help_text="GA4 Ölçüm ID (G-XXXXXXXXXX)", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="google_search_console_meta",
            field=models.CharField(
                blank=True,
                help_text="Google Search Console doğrulama meta content değeri",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
