# Generated by Django 5.2.11 on 2026-03-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_contact_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="answered",
            field=models.BooleanField(default=False, verbose_name="Cevaplandı"),
        ),
    ]
