"""
Django settings for marifetli_project project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY", default="django-insecure-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="localhost,127.0.0.1", cast=Csv())


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "social_django",
    # Local apps
    "core",
    "users",
    "categories",
    "questions",
    "answers",
    "comments",
    "favorites",
    "reputation",
    "notifications",
    "moderation",
    "cronjobs",
    "onboarding",
    "achievements",
    "emails",
    "blog",
    "communities",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "social_django.middleware.SocialAuthExceptionMiddleware",
    "users.middleware.ClearSessionBeforeGoogleOAuthMiddleware",
]

ROOT_URLCONF = "marifetli_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# Jazzmin (Admin tema)
JAZZMIN_SETTINGS = {
    "site_title": "Marifetli Admin",
    "site_header": "Marifetli",
    "site_brand": "Marifetli",
    "site_logo_classes": "img-circle",
    "welcome_sign": "Marifetli Yönetim Paneline Hoş Geldiniz",
    "copyright": "Marifetli",
    "search_model": ["users.user", "questions.question"],
    "topmenu_links": [
        {"name": "Ana Sayfa", "url": "admin:index"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "icons": {
        "auth": "fas fa-users-cog",
        "users": "fas fa-user",
        "users.user": "fas fa-user",
        "questions": "fas fa-question-circle",
        "questions.question": "fas fa-question",
        "answers": "fas fa-reply",
        "categories": "fas fa-folder",
        "favorites": "fas fa-bookmark",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
}

WSGI_APPLICATION = "marifetli_project.wsgi.application"

# Custom User Model
AUTH_USER_MODEL = "users.User"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_ENGINE = config("DATABASE_ENGINE", default="django.db.backends.sqlite3")
if "postgresql" in DATABASE_ENGINE:
    sslmode = config("DATABASE_SSLMODE", default=None)
    db_options = {"sslmode": sslmode} if sslmode else {}
    DATABASES = {
        "default": {
            "ENGINE": DATABASE_ENGINE,
            "NAME": config("DATABASE_NAME", default="marifetli"),
            "USER": config("DATABASE_USER", default="postgres"),
            "PASSWORD": config("DATABASE_PASSWORD", default=""),
            "HOST": config("DATABASE_HOST", default="localhost"),
            "PORT": config("DATABASE_PORT", default="5432"),
            "OPTIONS": db_options if db_options else {},
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files - DigitalOcean Spaces (S3-compatible)
USE_S3_MEDIA = config("AWS_ACCESS_KEY_ID", default=None)
if USE_S3_MEDIA:
    AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_REGION_NAME = config("AWS_S3_REGION_NAME")
    AWS_S3_ENDPOINT_URL = config("AWS_S3_ENDPOINT_URL").rstrip("/")
    AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.{AWS_S3_REGION_NAME}.digitaloceanspaces.com"
    AWS_S3_OBJECT_PARAMETERS = {"CacheControl": "max-age=86400"}
    AWS_DEFAULT_ACL = "public-read"
    AWS_QUERYSTRING_AUTH = False
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "bucket_name": AWS_STORAGE_BUCKET_NAME,
                "region_name": AWS_S3_REGION_NAME,
                "endpoint_url": AWS_S3_ENDPOINT_URL,
                "custom_domain": AWS_S3_CUSTOM_DOMAIN,
                "location": "media",
                "object_parameters": AWS_S3_OBJECT_PARAMETERS,
                "default_acl": AWS_DEFAULT_ACL,
                "querystring_auth": AWS_QUERYSTRING_AUTH,
                "file_overwrite": False,
            },
        },
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }
else:
    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django REST Framework Settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
}

# JWT Settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": SECRET_KEY,
    "AUDIENCE": None,
    "ISSUER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
}

# Frontend URL - .env'den (e-posta linkleri, OAuth redirect, CORS için tek kaynak)
FRONTEND_URL = config("FRONTEND_URL", default="http://localhost:3000")
# Backend URL - e-posta şablonlarındaki logo vb. mutlak URL'ler için (örn. https://api.marifetli.com.tr)
BACKEND_URL = config("BACKEND_URL", default="").strip().rstrip("/") or None

# CORS - FRONTEND_URL .env'de tanımlı; aynı domain'in www / www'süz hali de eklenir
def _cors_origins_list():
    base = FRONTEND_URL.rstrip("/")
    origins = ["http://localhost:3000", "http://127.0.0.1:3000", base]
    if base.startswith("https://www."):
        origins.append(base.replace("https://www.", "https://", 1))
    elif base.startswith("https://") and "www." not in base:
        origins.append(base.replace("https://", "https://www.", 1))
    return ",".join(origins)

CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS",
    default=_cors_origins_list(),
    cast=Csv()
)
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = ["DELETE", "GET", "OPTIONS", "PATCH", "POST", "PUT"]
CORS_ALLOW_HEADERS = ["accept", "accept-encoding", "authorization", "content-type", "origin", "user-agent", "x-csrftoken", "x-requested-with"]
CORS_EXPOSE_HEADERS = ["content-type", "content-length"]

# CSRF - Admin ve form POST'ları için Origin güvenilir listesi (Django 4+)
# Canlıda BACKEND_URL veya CSRF_TRUSTED_ORIGINS tanımlayın (örn. Railway'de BACKEND_URL=https://web-production-5404d.up.railway.app)
def _csrf_trusted_origins_list():
    origins = ["http://localhost:8000", "http://127.0.0.1:8000"]
    backend_url = (BACKEND_URL or "").strip().rstrip("/")
    if backend_url:
        origins.append(backend_url)
    # ALLOWED_HOSTS'tan ilk non-local host varsa https ile ekle (canlıda BACKEND_URL unutulursa)
    for h in ALLOWED_HOSTS:
        if h and h not in ("localhost", "127.0.0.1") and "." in h:
            origins.append(f"https://{h}")
            break
    frontend = FRONTEND_URL.rstrip("/")
    if frontend and frontend not in origins:
        origins.append(frontend)
    return origins

CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS",
    default=",".join(_csrf_trusted_origins_list()),
    cast=Csv(),
)

# Cookie / Security (production)
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SAMESITE = "Lax"
# OAuth akışında session'ın kaybolmaması için her istekte kaydet
SESSION_SAVE_EVERY_REQUEST = True

if not DEBUG:
    # Railway proxy SSL'i sonlandırır; container'a HTTP gelir. Redirect kapatıyoruz ki healthcheck 200 alsın.
    SECURE_SSL_REDIRECT = False
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Social Auth Settings
AUTHENTICATION_BACKENDS = [
    "social_core.backends.google.GoogleOAuth2",
    "django.contrib.auth.backends.ModelBackend",
]

# Google OAuth - .env'den oku (Google Cloud Console'dan Client ID ve Secret al)
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = config("SOCIAL_AUTH_GOOGLE_OAUTH2_KEY", default="")
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = config("SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET", default="")

# OAuth sonrası JWT üretip frontend'e yönlendirilecek URL (backend view).
# Tam URL kullanıyoruz ki Google'dan dönüşte aynı domain'e gidilsin, session cookie gitsin.
BACKEND_BASE = (config("BACKEND_URL", default="").strip().rstrip("/") or "http://localhost:8000")
LOGIN_REDIRECT_URL = f"{BACKEND_BASE}/api/auth/oauth-success/"
# OAuth hata durumunda: False = frontend'e yönlendir, True = 500 + terminalde tam hata (debug için)
SOCIAL_AUTH_RAISE_EXCEPTIONS = config("SOCIAL_AUTH_RAISE_EXCEPTIONS", default=False, cast=bool)
LOGIN_ERROR_URL = "/api/auth/oauth-error/"

SOCIAL_AUTH_PIPELINE = (
    "social_core.pipeline.social_auth.social_details",
    "social_core.pipeline.social_auth.social_uid",
    "social_core.pipeline.social_auth.auth_allowed",
    "social_core.pipeline.social_auth.social_user",
    "users.pipeline.get_username_from_email",
    "social_core.pipeline.user.get_username",
    "users.pipeline.create_user_with_email",
    "social_core.pipeline.social_auth.associate_user",
    "social_core.pipeline.social_auth.load_extra_data",
    "social_core.pipeline.user.user_details",
    "users.pipeline.set_social_user_verified",
    "users.pipeline.redirect_to_frontend_with_jwt",  # JWT + redirect; session kullanılmaz
)

SOCIAL_AUTH_POSTGRES_JSONFIELD = True

# Email / SMTP settings (use .env via python-decouple)
SMTP2GO_API_KEY = config("SMTP2GO_API_KEY", default="")
SMTP2GO_FROM_EMAIL = config("SMTP2GO_FROM_EMAIL", default="noreply@marifetli.com")

# Firebase Cloud Messaging (push bildirimleri) - .env'e FIREBASE_CREDENTIALS_PATH=path/to/serviceAccountKey.json ekle
FIREBASE_CREDENTIALS_PATH = config("FIREBASE_CREDENTIALS_PATH", default="")

# Cache - yük azaltma ve ölçeklenebilirlik (Redis önerilir)
# .env: REDIS_URL=redis://127.0.0.1:6379/0 (veya Railway/Upstash Redis URL)
REDIS_URL = config("REDIS_URL", default="")
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "marifetli-default",
        }
    }

# Cache TTL (saniye): soru listesi vb. liste sayfaları
CACHE_TTL_QUESTION_LIST = config("CACHE_TTL_QUESTION_LIST", default=60, cast=int)  # 1 dakika
CACHE_TTL_QUESTION_DETAIL = config("CACHE_TTL_QUESTION_DETAIL", default=30, cast=int)  # 30 sn

# Moderation - LLM servisi. POST { "text": "..." } -> { "status": "ONAY"|"RED", "bad_words": [] }
# RED + bad_words: önerilen kelimeler SuggestedBadWord'e pending yazılır, admin onayı ile BadWord'e eklenir.
# config'ten (env) verilmezse boş; boşsa LLM çağrısı yapılmaz.
MODERATION_LLM_URL = config("MODERATION_LLM_URL", default="").strip()
MODERATION_LLM_TIMEOUT = config("MODERATION_LLM_TIMEOUT", default=10, cast=int)
# Bildirimlerde "moderatör" olarak kullanılacak sistem kullanıcı kullanıcı adı (yoksa ilk superuser)
MODERATOR_SYSTEM_USERNAME = config("MODERATOR_SYSTEM_USERNAME", default="system_moderator")