# Generated by Django 5.2.11 on 2026-04-16 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0007_add_hierarchical_categories"),
        ("category_experts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="categoryexpertquery",
            name="cexquery_user_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="categoryexpertquery",
            name="cexquery_created_idx",
        ),
        migrations.AddIndex(
            model_name="categoryexpertquery",
            index=models.Index(
                fields=["user", "-created_at"], name="category_ex_user_id_8db93e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="categoryexpertquery",
            index=models.Index(
                fields=["-created_at"], name="category_ex_created_164c89_idx"
            ),
        ),
    ]
