# Generated by Django 5.2.11 on 2026-03-16 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="logentry",
            new_name="logs_logent_created_fb99ec_idx",
            old_name="logs_logent_created_8b0b0d_idx",
        ),
        migrations.RenameIndex(
            model_name="logentry",
            new_name="logs_logent_level_b0de8a_idx",
            old_name="logs_logent_level_2a0e0a_idx",
        ),
        migrations.RenameIndex(
            model_name="logentry",
            new_name="logs_logent_source_cad1e7_idx",
            old_name="logs_logent_source_1c1e1b_idx",
        ),
    ]
