# Generated by Django 5.2.11 on 2026-03-01 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("category", "Kategori seç (mevcut kategoriler)"),
                            ("tag", "Etiket seç (mevcut etiketler)"),
                            ("custom", "Özel seçenekler (admin tanımlar)"),
                        ],
                        default="custom",
                        max_length=20,
                        verbose_name="Tip",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Sıra")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "max_selections",
                    models.PositiveIntegerField(
                        default=0, help_text="0 = sınırsız", verbose_name="Maks. seçim"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Onboarding Adımı",
                "verbose_name_plural": "Onboarding Adımları",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200, verbose_name="Metin")),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        help_text="Boş bırakılırsa otomatik oluşturulur",
                        max_length=100,
                        verbose_name="Değer (slug)",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Sıra")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="onboarding.onboardingstep",
                        verbose_name="Adım",
                    ),
                ),
            ],
            options={
                "verbose_name": "Onboarding Seçeneği",
                "verbose_name_plural": "Onboarding Seçenekleri",
                "ordering": ["step", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="UserOnboarding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tamamlanma"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı Onboarding",
                "verbose_name_plural": "Kullanıcı Onboarding",
            },
        ),
        migrations.CreateModel(
            name="UserOnboardingSelection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selections",
                        to="onboarding.onboardingchoice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_selections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı Onboarding Seçimi",
                "verbose_name_plural": "Kullanıcı Onboarding Seçimleri",
                "unique_together": {("user", "choice")},
            },
        ),
    ]
