# Generated by Django 5.2.11 on 2026-04-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MebOgretimProgrami",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "egitim_yili",
                    models.CharField(help_text="Örn: 2025/2026", max_length=20),
                ),
                (
                    "seviye",
                    models.CharField(
                        choices=[
                            ("okul_oncesi", "Okul Öncesi"),
                            ("temel_egitim", "Temel Eğitim"),
                            ("ortaogretim", "Ortaöğretim"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sinif",
                    models.CharField(
                        help_text="Örn: 1. Sınıf (İlkokul), 36-48 Ay", max_length=50
                    ),
                ),
                ("ders_adi", models.CharField(max_length=200)),
                (
                    "ders_slug",
                    models.CharField(
                        help_text="URL slug — tymm.meb.gov.tr'deki ders slug'ı",
                        max_length=200,
                    ),
                ),
                (
                    "kaynak_url",
                    models.URLField(
                        help_text="tymm.meb.gov.tr öğretim programı sayfası",
                        max_length=500,
                    ),
                ),
                (
                    "klasor_yolu",
                    models.CharField(
                        help_text="AnythingLLM klasör yolu — örn: 2025-2026/ilkokul/1.sinif/matematik",
                        max_length=300,
                    ),
                ),
                ("aktif", models.BooleanField(default=True)),
                ("olusturuldu", models.DateTimeField(auto_now_add=True)),
                ("guncellendi", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "MEB Öğretim Programı",
                "verbose_name_plural": "MEB Öğretim Programları",
                "ordering": ["egitim_yili", "seviye", "sinif", "ders_adi"],
                "unique_together": {("egitim_yili", "ders_slug", "kaynak_url")},
            },
        ),
    ]
