# Generated by Django 5.2.11 on 2026-04-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meb_programlari", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mebogretimprogrami",
            options={
                "ordering": ["egitim_yili", "seviye", "sinif", "ders_adi", "unite_adi"],
                "verbose_name": "MEB Öğretim Programı",
                "verbose_name_plural": "MEB Öğretim Programları",
            },
        ),
        migrations.AddField(
            model_name="mebogretimprogrami",
            name="unite_adi",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Örn: 1. ÜNİTE: BİLİME YOLCULUK",
                max_length=300,
            ),
        ),
    ]
