# Generated by Django 5.2.11 on 2026-04-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meb_programlari", "0002_alter_mebogretimprogrami_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mebogretimprogrami",
            name="anythingllm_yuklendi",
            field=models.BooleanField(
                default=False, help_text="AnythingLLM'e yüklenip embed edildiyse True"
            ),
        ),
    ]
