# Generated by Django 5.2.11 on 2026-04-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meb_programlari", "0003_mebogretimprogrami_anythingllm_yuklendi"),
    ]

    operations = [
        migrations.AddField(
            model_name="mebogretimprogrami",
            name="dosya_yolu",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Çekilen içeriğin kaydedildiği .md dosyası",
                max_length=500,
            ),
        ),
    ]
