# Generated by Django 5.2.11 on 2026-03-01 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("answers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_notifications", models.BooleanField(default=True)),
                ("push_notifications", models.BooleanField(default=True)),
                ("desktop_notifications", models.BooleanField(default=True)),
                ("notify_on_answer", models.BooleanField(default=True)),
                ("notify_on_like", models.BooleanField(default=True)),
                ("notify_on_follow", models.BooleanField(default=True)),
                ("notify_mention", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("answer", "Question Answered"),
                            ("like_question", "Question Liked"),
                            ("like_answer", "Answer Liked"),
                            ("follow", "User Followed"),
                            ("mention", "User Mentioned"),
                            ("best_answer", "Best Answer Selected"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "answer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="answers.answer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
