# Generated by Django 5.2.11 on 2026-03-04 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("answer", "Question Answered"),
                    ("like_question", "Question Liked"),
                    ("like_answer", "Answer Liked"),
                    ("follow", "User Followed"),
                    ("mention", "User Mentioned"),
                    ("best_answer", "Best Answer Selected"),
                    ("followed_post", "Followed User Posted"),
                ],
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="FCMDeviceToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255, unique=True)),
                ("device_name", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fcm_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "FCM Cihaz Token",
                "verbose_name_plural": "FCM Cihaz Tokenları",
            },
        ),
    ]
