# Generated by Django 5.2.11 on 2026-03-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0006_community_join_request_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("answer", "Question Answered"),
                    ("like_question", "Question Liked"),
                    ("like_answer", "Answer Liked"),
                    ("follow", "User Followed"),
                    ("mention", "User Mentioned"),
                    ("best_answer", "Best Answer Selected"),
                    ("followed_post", "Followed User Posted"),
                    ("moderation_removed", "Moderatör tarafından içerik kaldırıldı"),
                    ("community_join_request", "Topluluğa katılım talebi"),
                    ("community_post_removed", "Gönderi topluluktan kaldırıldı"),
                ],
                max_length=32,
            ),
        ),
    ]
