# Generated by Django 5.x style migration

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("kids", "0059_kidsclassdocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="KidsClassDocumentFolder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kids_class_document_folders_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kids_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_folders",
                        to="kids.kidsclass",
                    ),
                ),
            ],
            options={
                "db_table": "kids_class_document_folders",
                "ordering": ["name", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="kidsclassdocumentfolder",
            constraint=models.UniqueConstraint(
                fields=("kids_class", "name"),
                name="kids_class_document_folder_class_name_uniq",
            ),
        ),
        migrations.AddField(
            model_name="kidsclassdocument",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="kids.kidsclassdocumentfolder",
            ),
        ),
    ]
