# Generated by Django 5.2.11 on 2026-04-16 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kids", "0061_kidsclassdocumentfolder_parent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="kidsnotification",
            name="kids_notif_recipient_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="kidsnotification",
            name="kids_notif_recipient_read_idx",
        ),
        migrations.RenameIndex(
            model_name="kidsgamesession",
            new_name="kids_game_s_student_8c509a_idx",
            old_name="kids_game_se_student_0094be_idx",
        ),
        migrations.RenameIndex(
            model_name="kidsgamesession",
            new_name="kids_game_s_student_3e739c_idx",
            old_name="kids_game_se_student_5f8d73_idx",
        ),
        migrations.RenameIndex(
            model_name="kidsgamesession",
            new_name="kids_game_s_game_id_5edcbf_idx",
            old_name="kids_game_se_game_id_9f355a_idx",
        ),
        migrations.RenameIndex(
            model_name="kidskindergartendailyrecord",
            new_name="kids_kg_dai_kids_cl_21545f_idx",
            old_name="kids_kg_daily_class_date_idx",
        ),
        migrations.RenameIndex(
            model_name="kidskindergartendailyrecord",
            new_name="kids_kg_dai_student_618acd_idx",
            old_name="kids_kg_daily_student_date_idx",
        ),
        migrations.RenameIndex(
            model_name="mebschooldirectory",
            new_name="kids_meb_sc_provinc_043301_idx",
            old_name="kids_meb_sc_provin_0a1b2c_idx",
        ),
        migrations.RenameIndex(
            model_name="mebschooldirectory",
            new_name="kids_meb_sc_il_plak_a89896_idx",
            old_name="kids_meb_sc_il_pla_0d1e2f_idx",
        ),
        migrations.AddField(
            model_name="kidsassignment",
            name="peer_submissions_visible",
            field=models.BooleanField(
                default=False,
                help_text="True ise aynı sınıftaki öğrenciler bu challenge'a ait diğer teslimatleri görebilir.",
                verbose_name="öğrenciler birbirinin çalışmalarını görebilir",
            ),
        ),
        migrations.AlterField(
            model_name="kidschallenge",
            name="parent_rejection_note",
            field=models.TextField(blank=True, verbose_name="veli red notu"),
        ),
        migrations.AlterField(
            model_name="kidschallenge",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_teacher", "Öğretmen onayı bekliyor"),
                    ("pending_parent", "Veli onayı bekliyor"),
                    ("rejected", "Reddedildi"),
                    ("active", "Devam ediyor"),
                    ("ended", "Sona erdi"),
                ],
                db_index=True,
                default="pending_teacher",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="kidschallengeinvite",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Bekliyor"),
                    ("accepted", "Kabul"),
                    ("declined", "Red"),
                    ("revoked", "Geri çekildi"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="kidskindergartendailyrecord",
            name="meal_slots",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Örn. [{"label": "Kahvaltı", "ok": true}, ...]. Boşsa yalnızca meal_ok özeti kullanılır.',
                verbose_name="öğün dilimleri",
            ),
        ),
        migrations.AlterField(
            model_name="kidskindergartendailyrecord",
            name="nap_slots",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Örn. [{"label": "Öğle uykusu", "ok": true}, ...]. Boşsa yalnızca nap_ok özeti kullanılır.',
                verbose_name="uyku dilimleri",
            ),
        ),
        migrations.AlterField(
            model_name="kidsnotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("kids_new_assignment", "Yeni proje"),
                    ("kids_new_test", "Yeni test"),
                    ("kids_submission_received", "Proje teslimi"),
                    ("kids_new_homework", "Yeni ödev"),
                    ("kids_new_homework_parent", "Yeni ödev (veli)"),
                    (
                        "kids_homework_parent_review_required",
                        "Ödev veli onayı bekliyor",
                    ),
                    (
                        "kids_homework_parent_approved_for_teacher",
                        "Ödev veli onayı öğretmene iletildi",
                    ),
                    ("kids_homework_teacher_reviewed", "Ödev öğretmen değerlendirmesi"),
                    ("kids_challenge_pending_teacher", "Yarışma öğretmen onayında"),
                    ("kids_challenge_approved", "Yarışma onaylandı"),
                    ("kids_challenge_rejected", "Yarışma reddedildi"),
                    ("kids_challenge_invite", "Yarışma daveti"),
                    ("kids_challenge_pending_parent", "Serbest yarışma veli onayında"),
                    ("kids_new_message", "Yeni mesaj"),
                    ("kids_new_announcement", "Yeni duyuru"),
                    ("kids_assignment_due_soon", "Son teslim yaklaşıyor"),
                    ("kids_assignment_late_submitted", "Geç teslim alındı"),
                    (
                        "kids_assignment_graded_with_rubric",
                        "Rubrik değerlendirmesi yayınlandı",
                    ),
                    ("kids_kg_child_arrived", "Anaokulu: çocuk okula geldi"),
                    ("kids_kg_end_of_day", "Anaokulu: gün sonu özeti"),
                    ("kids_kg_monthly_absence", "Anaokulu: aylık devamsızlık"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="kidstest",
            name="kids_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="kids.kidsclass",
            ),
        ),
        migrations.AlterField(
            model_name="kidsuser",
            name="parent_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Ana `users` tablosundaki veli; davet akışı ile bağlanır.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kids_children_accounts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="veli hesabı",
            ),
        ),
        migrations.AlterField(
            model_name="kidsuser",
            name="role",
            field=models.CharField(
                choices=[("student", "Öğrenci")],
                db_index=True,
                default="student",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="kidsnotification",
            index=models.Index(
                fields=["recipient_student", "created_at"],
                name="kids_notifi_recipie_95af65_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="kidsnotification",
            index=models.Index(
                fields=["recipient_student", "is_read"],
                name="kids_notifi_recipie_602723_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="kidsnotification",
            index=models.Index(
                fields=["recipient_user", "created_at"],
                name="kids_notifi_recipie_222069_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="kidsnotification",
            index=models.Index(
                fields=["recipient_user", "is_read"],
                name="kids_notifi_recipie_c0726f_idx",
            ),
        ),
    ]
