# Generated by Django 5.2.11 on 2026-04-17 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kids", "0063_seed_reading_games"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadingStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="başlık"),
                ),
                ("text", models.TextField(verbose_name="hikaye metni")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Kolay"),
                            ("medium", "Orta"),
                            ("hard", "Zor"),
                        ],
                        db_index=True,
                        default="easy",
                        max_length=16,
                    ),
                ),
                (
                    "grade_level",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=1, verbose_name="sınıf seviyesi"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Okuma hikayesi",
                "verbose_name_plural": "Okuma hikayeleri",
                "db_table": "kids_reading_stories",
                "ordering": ["difficulty", "grade_level", "id"],
            },
        ),
        migrations.CreateModel(
            name="ReadingWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word",
                    models.CharField(
                        db_index=True, max_length=60, verbose_name="kelime"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Kolay"),
                            ("medium", "Orta"),
                            ("hard", "Zor"),
                        ],
                        db_index=True,
                        default="easy",
                        max_length=16,
                    ),
                ),
                (
                    "grade_level",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=1, verbose_name="sınıf seviyesi"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Okuma kelimesi",
                "verbose_name_plural": "Okuma kelimeleri",
                "db_table": "kids_reading_words",
                "ordering": ["difficulty", "grade_level", "word"],
            },
        ),
        migrations.CreateModel(
            name="ReadingStoryQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=300, verbose_name="soru")),
                ("option_a", models.CharField(max_length=150, verbose_name="A şıkkı")),
                ("option_b", models.CharField(max_length=150, verbose_name="B şıkkı")),
                ("option_c", models.CharField(max_length=150, verbose_name="C şıkkı")),
                (
                    "correct",
                    models.CharField(
                        choices=[("a", "A"), ("b", "B"), ("c", "C")],
                        max_length=1,
                        verbose_name="doğru şık",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="kids.readingstory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hikaye sorusu",
                "verbose_name_plural": "Hikaye soruları",
                "db_table": "kids_reading_story_questions",
                "ordering": ["order", "id"],
            },
        ),
    ]
